name = "MPCJulia"
uuid = "ac1e6813-e7b0-43e9-9282-ce72bd12db4d"
authors = ["Sharfi Rahman"]
version = "1.0.0-DEV"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FreeType = "b38be410-82b0-50bf-ab77-7b57e271db43"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
ModelPredictiveControl = "61f9bdb8-6ae4-484a-811f-bbf86720c31c"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Blink = "0.12.5"
CairoMakie = "0.15.6"
CalculusWithJulia = "0.2.9"
ControlSystems = "1.14.0"
ControlSystemsBase = "1.18.2"
FileIO = "1.16.5"
FreeType = "4.1.1"
Ipopt = "1.10.6"
JuMP = "1.28.0"
LinearAlgebra = "1.11.0"
Meshes = "0.55.2"
ModelPredictiveControl = "1.8.2"
Plotly = "0.4.1"
PlotlyJS = "0.18.17"
Plots = "1.40.18"
Revise = "3.9.0"
StaticArrays = "1.9.14"
UnicodePlots = "3.8.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
